### ISSUE TITLE
Text in teamstyle after ToX repeats the team size

### ISSUE THREAD

**Issue by D4mnX** [Eluinhost/Match-Calendar#145]
`Apr 25 14:45 UTC EU - D4's #199 - To2 Double Dates - Starter Elytra, Dragon Rush [1.9] [TS3/Working Microphone REQUIRED]`

was parsed as:

![Screenshot of parsed result](http://i.imgur.com/1YaRrEF.png)

Not too sure how the calendar tripped there? IIRC if it can't parse it, it just displays it raw, even more confusing as ToX is displayed as "Chosen ToX".

**Comment by Eluinhost** [comment]
If detects teamsizes from the regex /To[X\d]+/. It removes it from the string and passes the remains to the game type parsers. CHOSEN is matched for 'c' as well as the special case ''. If none of them are matched then it'll use the original string. Not sure why `To2 Double Dates` would cause issues though

**Comment by Eluinhost** [comment]
Pushing to live now
