### ISSUE TITLE
Stop synchronously loading match data upon every page load

### ISSUE THREAD

**Issue by dellis23** [Eluinhost/Match-Calendar#146]
Can you come up with a job that loads the data once a minute or so, rather than having every user request it on every page load?  This will help reduce the search load on reddit.

**Comment by dellis23** [comment]
Oh, and apparently polling as well.

**Comment by Eluinhost** [comment]
Yeah it was something I was meaning to do a while back, I'll get around to implementing it in the morning. Sorry for letting it get to be a problem before tackling it. Do you know if there is any thought put towards adding a 'by flair' endpoint? It's something I've seen a few people interested in and would move some processing requirements away from the search endpoints

**Comment by dellis23** [comment]
No worries!  Thanks for being so responsive.

I haven't heard anything about a "by flair" endpoint, but I'll let you know if I do.
